### ISSUE TITLE
"TypeError: Cannot redefine property: id" with ngIf

### ISSUE THREAD

**Issue by taujoey** [dhilt/ngx-ui-scroll#270]
Hi,

I know it is a little messy issue description, feel free to split this into multiples or mark as duplicate, i didnt really know how to present it to you.

I'm still working on [this](https://github.com/dhilt/ngx-ui-scroll/issues/267) card-view like feature (grouping), and i ran into a problem mentioned in the title. 
I try to switch between the list and card view with ngIf (maybe with ngSwitch later on), but i ran into the "redefine" problem. I found  [this](https://github.com/dhilt/ngx-ui-scroll/issues/244) topic, tried to use the reset method, but did not help.
After this I tried to put together a minimal stackblitz example for you, but i ran into another problem xD

Link: [Stackblitz demo (bad)](https://stackblitz.com/edit/angular-ngx-ui-scroll-grouping-flex-jnrkye?file=src%2Fapp%2Fapp.component.html) 
I can hide the list with the flip button, but after pressing again, it gives me this error:
**"ERROR Error: _this.source[reactive].set is not a function"**
I have no idea what it means.

I tried to create an example from another stackblitz example of yours (older component versions), and there it works:
Link: [StackBlitz demo (good)](https://stackblitz.com/edit/ngx-ui-scroll-1-11-0-angular-11-bsw87n?file=src%2Fapp%2Fapp.component.html)

So in the bad stackblitz demo i changed the ngx-ui-scroll version back to "^1.11.0" from the "2.1.0-beta.2", and with that it works.

I use the newest version (2.1.0-beta.2) too locally with the latest angular stack, but because of this "reactive" error i can't reproduce the "redefine property" error on stackblitz to show it to you.

Could you please take a look?
Thanks! :)

**Comment by taujoey** [comment]
Hi,

I reversed back locally too to version 1.11.1, and the ngif approach (with viewchild) works flawlessly without any errors.
Upgraded back to version 2.0.3, and the "TypeError: can't redefine non-configurable property "id"" error is back.

Here are my main components:
```
Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@angular/flex-layout            12.0.0-beta.34
@nguniversal/express-engine     7.1.1
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by dhilt** [comment]
@taujoey The "source[reactive].set is not a function" error seems an important problem, I'm looking at it, thanks! The "can't redefine non-configurable property" error relates to the same piece of logic, so I think I'll fix both, but the "source[reactive].set is not a function" problem will go first as I can reproduce it.

**Comment by taujoey** [comment]
Cool, thank You very much! :)

**Comment by dhilt** [comment]
@taujoey ngx-ui-scroll v2.1.0 is on npm, it fixes the first problem, may I ask you to look at the second one? Is it still there or fixed?

**Comment by taujoey** [comment]
Hi,

Thanks!
The second problem locally on my machine is still there after upgrading to v2.1.0.
On stackblitz, the first and second problems are both gone after upgrading the bad demo, so i'll try to figure it out, what's the difference and fix locally, or reproduce on stackblitz. 
I'll get back to You.

**Comment by dhilt** [comment]
@taujoey "Cannot redefine property: id" scares me. If you can cut and share your app, I will look at it.

**Comment by dpraul** [comment]
I am also still encountering the "Cannot redefine property: id" issue on v2.1.0. I will try to put together a demo that reproduces it.

**Comment by dhilt** [comment]
@dpraul I'm working on https://github.com/dhilt/vscroll/issues/17 issue and I faced redefine problem in a scenario very similar to what we are discussing here. I decided to make an interim release containing the fix for this particular problem. It most likely should cover your case. Could you try [ ngx-ui-scroll v2.1.2](https://www.npmjs.com/package/ngx-ui-scroll/v/2.1.2)?

**Comment by dpraul** [comment]
@dhilt 2.1.2 fixes it for me! Nicely done!

**Comment by dhilt** [comment]
ngx-ui-scroll v2.2.0 is released, it contains some additional changes related to this issue and is recommended for use

**Comment by dpraul** [comment]
2.2.0 works great! Thanks for your continued work here :)

**Comment by taujoey** [comment]
It works for me now too, thanks! :)
